---
 - name: run virtual router containers
   docker_container:
     name: "{{ inventory_hostname }}"
     image: "{{ docker_image }}"
     privileged: true
     state: started
     tty: true
     detach: true
   register: container
   until: container.ansible_facts.docker_container.State.Health.Status == "healthy"
   retries: 30
   delay: 60

 - name: Template vrxcon p2p links
   set_fact:
     xcon_p2p: "--p2p {% for p2p in xcon.p2p %}{{  p2p.a_device }}/{{ p2p.a_port }}--{{ p2p.b_device }}/{{ p2p.b_port }}{% if not loop.last %} {% endif %}{% endfor %}"
   run_once: true

# Need to work on getting links as a list using xcon_links
 - name: run xconnect containers
   docker_container:
     name: "peer-2-peer"
     image: vrnetlab/vr-xcon:latest
     command: "{{ xcon_p2p }}"
     links: "{{ xcon.links | default([]) }}"
   run_once: true
   

